// import { fab } from "@fortawesome/free-brands-svg-icons";
import {
  faHome,
  faSearch,
  faUserCircle,
  faEllipsisV,
  faShare,
  faAddressCard,
  faComments as faCommentsFull,
  faCommentDots,
  faPlus,
  faMinus,
  faHeart as faHeartfull,
  faTrashAlt,
  faBell as faBellFull,
  faPhotoVideo,
  faComment,
  faArrowLeft,
  faUserEdit,
  faSignOutAlt,
  faCamera,
  faMapMarkerAlt,
  faLink,
} from "@fortawesome/free-solid-svg-icons";
import {
  faComments,
  faHeart,
  faEye,
  faEyeSlash,
  faTimesCircle,
  faBell,
  faCalendar,
} from "@fortawesome/free-regular-svg-icons";

const icons = [
  faHome,
  faSearch,
  faAddressCard,
  faUserCircle,
  faComment,
  faComments,
  faCommentsFull,
  faHeart,
  faShare,
  faEllipsisV,
  faEye,
  faEyeSlash,
  faCommentDots,
  faTimesCircle,
  faPlus,
  faMinus,
  faHeartfull,
  faTrashAlt,
  faBellFull,
  faBell,
  faPhotoVideo,
  faArrowLeft,
  faCalendar,
  faUserEdit,
  faSignOutAlt,
  faCamera,
  faMapMarkerAlt,
  faLink,
];

export default icons;
