// User Types
export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const SET_USER = "SET_USER";
export const SET_PROFILE = "SET_PROFILE";
export const MARK_NOTIFICATIONS_READ = "MARK_NOTIFICATIONS_READ";
export const REMOVE_NOTIFICATION = "REMOVE_NOTIFICATION";
export const REMOVE_ALL_NOTIFICATIONS = "REMOVE_ALL_NOTIFICATIONS";
export const UPDATE_AVATAR = "UPDATE_AVATAR";
export const UPDATE_DETAILS = "UPDATE_DETAILS";
export const CLEAR_USER = "CLEAR_USER";

//Entry Types
export const ADD_ENTRY = "ADD_ENTRY";
export const ADD_COMMENT = "ADD_COMMENT";
export const SET_ENTRIES = "SET_ENTRIES";
export const SET_ENTRY_DETAILS = "SET_ENTRY_DETAILS";
export const REMOVE_ENTRY = "REMOVE_ENTRY";
export const OPEN_ENTRY_NEW = "OPEN_ENTRY_NEW";
export const CLOSE_ENTRY_NEW = "CLOSE_ENTRY_NEW";
export const UPDATE_LIKES_COUNT = "UPDATE_LIKES_COUNT";
